version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: ["--accounts", "10", "--defaultBalanceEther", "1000"]

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - ganache
